Frontend/feature/sing up
UB-ES-2024-A4/book-hub pull request #4
Opened 2024-10-21 22:05 UTC by Soliam006

### 1. **Formulario de Registro (SignUpForm Component)**
El componente `SignUpForm` es el formulario de registro contiene:

- **Campos de texto**: Para que el usuario introduzca su nombre de usuario, nombre, apellido, correo electrónico, y contraseña.
- **Validación del formulario**: Utiliza la librería `Zod` para validar los datos del formulario antes de enviarlos.
- **Componentes de UI reutilizables**: Como el componente `Input` para los campos de entrada. Se puede usar el *Input* para otros lugares en la WEB.

### 2. **Validación del Formulario con Zod**
El esquema de validación `singUpSchema` asegura que los datos introducidos por el usuario cumplan con ciertos requisitos:

- El **nombre de usuario** (`username`), **nombre** (`firstName`), y **apellido** (`lastName`) deben tener entre 3 y 20 caracteres.
- El **correo electrónico** debe ser un email válido.
- La **contraseña** debe tener entre 8 y 28 caracteres.

Este esquema se utiliza para validar los datos introducidos antes de intentar procesar el registro.

### 3. **Sin Funcionalidad Backend (Aún)**
Actualmente, no hay un backend funcional para manejar la lógica de creación de usuarios, pero he dejado el esqueleto para integrarlo en el futuro. Esto incluye:

- **Función CreateUser**: Una función asíncrona que, cuando el backend esté implementado, manejará la creación del usuario.
  - Si la validación falla, devuelve un error.
  - Si la validación es exitosa, redirige al usuario a la página de inicio de sesión (`/login`).

### Resumen del Pull Request:
- **Frontend**: Creación del formulario de registro con validación, sin funcionalidad completa aún.
- **Backend (Aún no funcional)**: Preparación para manejar la creación de usuarios.
- **Objetivo del Pull Request**: Establecer la base del registro de usuarios en la WEB, con validación y diseño listos para su futura implementación.

2024-10-21 22:54 UTC, gmarvega requested changes
Todo bonito👌🏻

> [!IMPORTANT]
> Quita el fichero .env

2024-10-21 22:54 UTC, gmarvega commented on .env
Aquest fitxer no l'has de pujar, hauries de tenir-lo en el [.gitignore](https://github.com/UB-ES-2024-A4/book-hub/blob/main/.gitignore)

2024-10-22 09:18 UTC, AlejandroDS1 requested changes
Descarga el .gitignore del main y elimina los archivos que no deberian de estar en github

2024-10-22 21:12 UTC, AlejandroDS1 approved these changes

2024-10-22 22:44 UTC, gmarvega approved these changes

2024-10-23 14:13 UTC, closed without merging